//Example:- 1

/*void main(){

  print("welcome");

  try {
    int div = 10 ~/ 0;
  }
  on NoSuchMethodError{
    print("Exception");
  }
  catch(obj){
    print("Exception occured $obj");
  }


}*/



// Example:- 2
//  :-  even if the  error is not solved it will print


/*void main() {
  print("Welcome");
  try {
    int div = 10 ~/ 0;
  }
  on NoSuchMethodError {
    print("Exception");
  }
  finally{
    print("Thank you");
  }

}*/




